version: "2.0"
services:
    nginx:
        image: nginx:latest
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - NGINX_HOST=phphub.net
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - /data/web/nginx/conf.d:/etc/nginx/conf.d
            - /data/web/nginx/logs:/data/nginx/logs
            - /data/web/htdocs:/data/htdocs
        links:
            - "php"
    php:
        image: feesn/php-yaf:74
        restart: always
        ports: 
            - "9000:9000"
        volumes: 
            - /data/web/htdocs:/data/htdocs
            - /data/web/php:/usr/local/etc/php
        links:
            - "mysql"
            - "redis"
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456      
        ports: 
            - "3306:3306"
        volumes: 
            - /data/web/mysql:/var/lib/mysql
    redis:
        image: redis:5.0
        restart: always
        ports: 
            - "6379:6379"
        volumes: 
            - /data/web/redis/data:/data
            - /data/web/redis/redis.conf:/usr/local/etc/redis/redis.conf
